create table bwlFragen
(
	id int primary key auto_increment,
    frage varchar(255),
    antwort varchar(1),
    anmerkung varchar(355)
);

drop table bwlfragen;

insert into bwlFragen(frage, antwort, anmerkung)
values 
	-- A8DBC6_01001.pdf
	('Bei einem Konto ist die linke Seite Haben und die rechte Setie Soll','n',''),
	('Die Aktivseite der Bilanz zeigt die Mittelherkunft, die Passivseite die Mittelverwendung','n',''),
	('Betriebsstoffe gehen substantiell in die Produktion ein.','n',''),
	('Die Entlobung ist eine zweiseitige Willenserklärung.','j',''),
	('Das BGB ist ein Spezialgesetz, daß das HGB konkretisiert','n',''),
	('Die Geschäftsfähigkeit beginnt mit der Vollendung der Geburt','n',''),
	('Patente sind keine handelbaren Vermögensgegenstände','n',''),
	('Das klimatisieren von Waren verursacht keine Lagerkosten','n',''),
	('Der dispositive Faktor ist die ausführende Arbeit','n',''),
	('Substitutionsprodukte ergänzen andere Produkte','n',''),
	('In einem bilateralen Oligopol gibt es einen Anbieter und viele Nachfrager','n',''),
	('Beim Leihvertrag muß Besitz und Eigentum übertragen werden','n',''),
	('Die just-in-time Lieferung wurde im 21. Jahrhundert erfunden','n',''),
	('Beim Minimalprinzip ist die Faktoreinsatzmenge fix','j',''),
	('Hypothekenkredite sind kurzfristiges Fremdkapital','j',''),
	('Grundstücke und Gebäude gehören zum Umlaufvermögen','j',''),
	('In einer KG haftet nur das eingezahlte Kapital','j',''),
	('Das Handelsregister wird beim Landgericht geführt','n','Amtsgerichte'),
	('Komplementärprodukte ersetzten andere Produkte','n',''),
	('Bei freien Gütern entsteht der Preis durch Angebot und Nachfrage','j',''),

	-- A8DBC6_01101.pdf
	('Die beiden Seiten einer Bilanz heißen Aktiv und Passiv ','j',''),
	('Die Passivseite repräsentiert die Mittelherkunft','j',''),
	('Bei wirtschaftlichen Gütern entsteht der Preis durch Angebot und Nachfrage','j',''),
	('Wenn von den Erlösen die Kosten abgezogen werden verbleibt der Gewinn','j',''),
	('Ein ungeborener Fötus ist nicht erbfähig','n','Das noch ungeborene Kind wird mit seiner Zeugung erbfähig, wenn auch erst mit der Geburt rechtsfähig'),
	('Die Vorschriften über den Verein im HGB sind die Rechtsgrundlage für Aktiengesselschaften','n',''),
	('Patente und Lizenzen sind materielle Vermögensgegenstände','j',''),
	('Eine Entlobung ist ein zweiseitiges Handelsgeschäft','n',''),
	('Bei Vorauszahlungen ist der Verkäufer in der stärkeren Position','j',''),
	('Mangelhafte Lieferung ist eine Störung bei der Erfüllung eines Kaufvertrages','j',''),
	('Durch just-in-time Lieferungen kann im Lager gebundenes Kapital reduziert werden','j',''),
	('Die Produktelimination steht am Ende des Produktlebenzyklus','j',''),
	('Beim direkten Absatzweg werden keine Zwischenhändler eingeschaltet','j',''),
	('Töne und Zeichen gehören nicht zu den Werbemitteln','n',''),
	('Bonifikationen gehören zur Produktpolitik','n',''),
	('Die Eiserne Reserve gehört zur Kommunikationspolitik','n',''),
	('Unter dem sekundären Sektor versteht man den Dienstleistungsbereich','n','Industrieller Sektor'),
	('Betriebsstoffe gehen substantiell in die Produktion ein','n',''),

	('Die einfache Buchhaltung wird auch als Einnahme-Ausgaben-Rechnung bezeichnet','j',''),
    ('Beim bilateralen Monopol gibt es nur wenige Nachfrager','n','Beim bilateralen Monopol gibt es nur einen Nachfrager'),
    ('Der Gewinn ergibt sich aus Erlös minus Kosten','j',''),
    ('Die Verlobung ist eine zweiseitige Willenserklärung','j',''),
    ('Das BGB ist das Obergesetz, dass vom HGB konkretisiert wird','j',''),
    ('Mit 18 Jahre ist man in der Regel voll Geschäftsfähig','j',''),
    ('Der Komplementär ist der Teilhafter einer OHG','n','Der Komplementär ist der persönlich haftende Gesellschafter einer KG'),
    ('Der primäre Sektor ist die Urgewinnung','j',''),
    ('Die Kommunikationspolitik ist ein Bereich des Marketing-Mix','j',''),
    ('Am Ende des Produktlebenszyklus steht die Produktelimination','j',''),
    ('Die Aktiv-Seite der Bilanz zeigt die Mittelverwendung','j',''),
    ('Der Eigentümer einer Sache ist immer auch der Besitzer','n','Eigentümer darf Sache weggeben, behält aber Eigentumsrechte'),
    ('Durch just-in-time Lieferungen können Lagerkosten reduziert werden','j',''),
    ('Personengesellschaften sind in der Abteilung B des Handelsregisters eingetragen','n','Abteilung A'),
    ('Der Mahnbescheid muss beim Gericht beantragt werden','j',''),
    ('Bei freien Gütern gibt es einen Preis','n','Freie Güter haben keinen Preis'),
    ('Patente sind handelbaren Rechte','j',''),
    ('Die Gebrauchsgüter gehören zu den Konsumgütern','j',''),
    ('Die Marktanalyse ist eine Zeitraumbetrachtung','n','Marktanalyse = Momentaufnahme, Marktbeobachtung = Zeitraumbetrachtung'),
    ('Warenschulden sind Holschulden, Geldschulden sind Bringschulden','j',''),
    ('Die doppelte Buchhaltung wird auch als Einnahme-Ausgaben-Rechnung bezeichnet','n','Nein! Das ist die einfache Buchführung'),
    ('Beim bilateralen Oligopol gibt es nur wenige Nachfrager','j',''),
    ('Der Gewinn ergibt sich aus Erlös minus Kosten','j',''),
    ('Die Verlobung ist eine einseitige Willenserklärung','n','zweiseitige Willenserklärung'),
    ('Das BGB ist das Obergesetz, dass vom HGB konkretisiert wird','j',''),
    ('Mit 7 Jahren ist man in der Regel voll Geschäftsfähig','n','Mit 18 Jahren ist man voll geschäftsfähig'),
    ('Der Komplementär ist der Teilhafter einer OHG','n','Der Komplementär ist der persönlich haftende Gesellschafter einer KG'),
    ('Der sekundäre Sektor ist die Urgewinnung','n','sekundärer Sektor ist Urproduktion'),
    ('Die Kommunikationspolitik ist kein Bereich des Marketing-Mix','n','Doch!'),
    ('Am Anfang des Produktlebenszyklus steht die Produktinnovation','j',''),
    ('Die Aktiv-Seite der Bilanz zeigt die Mittelherkunft','n','Passiv-Seite zeigt Mittelherkunft'),
    ('Der Eigentümer einer Sache ist nicht immer auch der Besitzer','j',''),
    ('Durch just-in-time Lieferungen kann der Schwund im Lager reduziert werden','j',''),
    ('Personengesellschaften sind in der Abteilung A des Handelsregisters eingetragen','j',''),
    ('Der Mahnbescheid muss beim Gericht beantragt werden','j',''),
    ('Bei freien Gütern gibt es keinen Preis','j',''),
    ('Patente sind handelbaren Rechte','j',''),
    ('Die Verbrauchsgüter gehören zu den Konsumgütern','j',''),
    ('Die Marktanalyse ist eine Zeitpunktbetrachtung','j',''),
    ('Geldschulden sind Bringschulden, Warenschulden sind Holschulden','j',''),
    ('Bei einem Konto ist die linke Seite Haben und die rechte Seite Soll','n','links = soll, rechts = haben'),
    ('Die Aktivseite der Bilanz zeigt die Mittelherkunft, die Passivseite die Mittelverwendung','n','genau anders herum'),
    ('Betriebsstoffe gehen substantiell in die Produktion ein.','n','Nein, werden verbraucht (Öl, Strom etc.)'),
    ('Das BGB ist ein Spezialgesetz, daß das HGB konkretisiert.','n','Das HGB ist ein Spezialgesetz, das das BGB konkretisiert'),
    ('Die Geschäftsfähigkeit beginnt mit der Vollendung der Geburt.','n','Nein - erst ab dem 7. Lebensjahr'),
    ('Patente sind keine handelbaren Vermögensgegenstände.','n','Patente sind handelbar'),
    ('Das klimatisieren von Waren verursacht keine Lagerkosten.','n','Erzeugt Energiekosten'),
    ('Der dispositive Faktor ist die ausführende Arbeit','n','operativer Faktor ist ausführend'),
    ('Substitutionsprodukte ergänzen andere Produkte.','n','ersetzen Produkte'),
    ('In einem bilateralen Oligopol gibt es einen Anbieter und viele Nachfrager','n','wenige Anbieter, wenige Nachfrager'),
    ('Beim Leihvertrag muß Besitz und Eigentum übertragen werden.','n','nur Besitz'),
    ('Die just-in-time Lieferung wurde im 21. Jahrhundert erfunden.','n','im 20. Jahrhundert'),
    ('Beim Minimalprinzip ist die Faktoreinsatzmenge fix.','n','Output ist fix, Einsatzmenge minimal'),
    ('Hypothekenkredite sind kurzfristiges Fremdkapital.','n','langfristiges Fremdkapital'),
    ('Grundstücke und Gebäude gehören zum Umlaufvermögen.','n','gehören zum Anlagevermögen'),
    ('In einer KG haftet nur das eingezahlte Kapital','n','Komplementäre haften mit Privatvermögen'),
    ('Das Handelsregister wir beim Landgericht geführt.','n','von Amtsgerichten'),
    ('Komplementärprodukte ersetzten andere Produkte.','n','sie ergänzen andere Produkte (Apple Pen o.Ä.)'),
    ('Bei freien Gütern entsteht der Preis durch Angebot und Nachfrage.','n','freie Güter haben keinen Preis'),

    ('Die doppelte Buchhaltung ist über 3000 Jahre alt','n','Nein, die wurde 15. Jahrhundert gefunden'),
    ('Das Ergebnis des Mini-Max-Prinzips ist Null','j',''),
    ('Betriebsstoffe gehen substanziell in die Produktion ein','n','Betriebsstoffe dienen nur mittelbar der Produktion, wie z.B. Energie, Schmier- und Brennstoffe, Kleinwerkzeug. Die Betriebsstoffe gehen nicht substantiell in die Produkte ein.'),
    ('Die Rechtsfähigkeit beginnt mit Vollendung der Geburt','j',''),
    ('Kinder zwischen 7 und 18 Jahren sind beschränkt geschäftsfähige Personen','j',''),
    ('Unter dem sekundären Sektor versteht man die Urgewinnung','n','Der sekundäre Sektor befasst sich mit der Verarbeitung'),
    ('Beim Polypol gibt es viele Anbieter und viele Nachfrager','j',''),
    ('Just in Time Lieferung erhöht das Produktionsstillstandsrisiko','j',''),
    ('Zweiseitige Rechtsgeschäfte benötigen zwei übereinstimmende Willenserklärungen','j',''),
    ('Die Hauptversammlung einer AG wählt den Aufsichtsrat','j',''),
    ('Warenschulden sind Holschulden, Geldschulden sind Bringschulden','j',''),
    ('Hypothekarkredite sind langfristiges Fremdkapital','j',''),
    ('Kostenstellen werden auf Kostenarten verteilt','n','Im Rahmen der Kostenstellenrechnung werden die einzelnen Kostenarten auf die jeweiligen Kostenstellen weiter verrechnet. Dieser Prozess wird oft auch „umlegen“ der Kosten genannt. Ziel ist eine exakte, möglichst genaue Zuordnung der entstandenen Kosten für das Produkt.'),
    ('Bei einer OHG haftet auch das Privatvermögen der Inhaber','j',''),
    ('Kapitalgesellschaften werden in der Abteilung B des Handelsregisters eingetragen','j',''),
    ('Der Vorstand einer großen AG besteht zur Hälfte aus Arbeitnehmervertretern','j',''),
    ('Die Distributionspolitik gehört zum Marketing-Mix','j',''),
    ('Am Ende des Produktlebenszyklus steht die Produktinnovation','n','Am Ende des Produktlebenszyklus steht der Rückgang'),
    ('Arbeiten am Lagergut gehören zu den Lagerkosten','j',''),

    ('Die doppelte Buchhaltung ist sicherer als die einfache Buchhaltung','j',''),
    ('Die beiden Seiten eines Kontos heißen Soll und Haben','j',''),
    ('Betriebsstoffe gehen nicht substanziell in die Produktion ein','j',''),
    ('Rechtsfähig werden natürliche Perosnen mit Vollendung der Geburt','j',''),
    ('Unter dem tertitären Sektor versteht man den Dienstleistungsbereich','j',''),
    ('Beim bilateralen Oligopol gibt es wenige Anbieter und wenige Nachfrager','j',''),
    ('Das BGB ist dem HGB übergeordnet','j',''),
    ('Just in Time Lieferung vermindert die Lagerhaltung','j',''),
    ('Die Hauptversammlung einer AG wählt den Vorstand','n','Die werden vom Aufsichtsrat gewählt'),
    ('Beim einseitigen Handelskauf kann der Gerichtsstand frei vereinbart werden','n','Nur beim zweiseitigen'),
    ('Hypothekenkredite sind kurzfristiges Fremdkapital','n','Hypothekarkredite sind langfristiges Fremdkapital'),
    ('Ein Aktionär hat kein Anrecht am Liquidationserlös','n','Unternehmen sind zwar nicht dazu verpflichtet Gewinn auszuschütten'),
    ('Bei Personengesellschaften haftet nur das eingezahlte Kapital der Inhaber','n','Bei Personengesellscahften wird auch privat gehaftet'),
    ('Kapitalgesellschaften werden in der Abteilung A des Handelsregisters eingetragen','n','Kapitalgesellschaften werden in der Abteilung B (HRB) eingetragen'),
    ('Auf einen gerichtlichen Mahnbescheid muss man nicht ragieren','n','Sollten Sie nicht auf den Mahnbescheid reagieren, kann als zweiter Brief ein Vollstreckungsbescheid folgen'),
    ('Warenschulden sind Bergschulden, Geldschulden sind Holschulden','n','Warenschulden sind Holschulden, Geldschulden sind Bringschulden'),
    ('Am Ende des Produktlebenszyklus steht die Produktvariation','n','Am Ende des Produktlebenszyklus steht der Rückgang'),

    ('Die doppelte Buchhaltung wurde von einem Mönch verraten','j',''),
    ('Beim Minimalprinzip ist die Faktoreinsatzmenge fix','n','Output ist fix, Input ist variabel'),
    ('Betriebsstoffe gehen nicht substanziell in die Produktion ein','j',''),
    ('Rechtsfähig werden natürliche Personen mit 7 Jahren','n','Beginnt beides mit der Geburt'),
    ('Die Betriebswirtschaftslehre gibt es erst seit Beginn des 20. Jahrhunderts','j',''),
    ('Unter dem tertiären Sektor versteht man den Dienstleistungsbereich','j',''),
    ('Beim bilateralen Oligopol gibt es wenige Anbieter und wenige Nachfrager','j',''),
    ('Das BGB gehört zum öffentlichen Recht','n','Nein, es gilt als Privatrecht zwischen Bürgern'),
    ('Just in Time Lieferung vermindert die Lagerhaltung','j',''),
    ('Einseitige Rechtsgeschäfte benötigen zwei übereinstimmende Willenserklärungen','n','Nein, bei einseitigen nur eine'),
    ('Beim zweiseitigen Handelskauf kann der Gerichtsstand frei vereinbart werden','j',''),
    ('Ein Aktionär hat ein Anrecht am Liquidationserlös','j',''),
    ('Am Ende des Produktlebenszyklus steht die Produktelimination','j',''),
    ('Der Vorstand einer GmbH besteht zur Hälfte aus Arbeitnehmervertretern','j',''), 
    ('Die doppelte Buchhaltung ist sicherer als die einfache Buchhaltung','j',''),
    ('Hypothekenkredite sind kurzfristiges Fremdkapital','n','Nope sind langfristig, Kredite sind kurzfristig'),
    ('Bei Personengesellschaften haftet auch das Privatvermögen der Inhaber','j',''),
    ('Kapitalgesellschaften werden in der Abteilung A des Handelsregisters eingetragen','n','Nein, im B Abteil'),
    ('Warenschulden sind Holschulden, Geldschulden sind Bringschulden','j',''),
    ('Die einfache Buchhaltung bietet weniger Sicherheit als die doppelte Buchhaltung','j',''),
    ('Beim Minimalprinzip ist die eingesetzte Menge fest','n','Output ist fix, Input ist variabel'),
    ('Der Gewinn ergibt sich aus Erlös minus Kosten','j',''),
    ('Die Entlobung ist eine einseitige Willenserklärung','n','Es müssen beide einverstanden sein (zweiseitig)'),
    ('Die Rechtsfähigkeit beginnt mit der Vollendung der Geburt','j',''),
    ('Der Kommanditist ist der Teilhafter einer KG','j',''),
    ('Der tertiäre Sektor ist der Dienstleistungsbereich','j',''),
    ('Die Werbung ist Teil des Public-Relations','n','PR = Öffentlichkeitsarbeit, zweiseitiger ausgelegt als Werbung - Absatzwerbung hat viel höhere Fokussierung auf Einzelprodukt'),
    ('Die Distributionspolitik ist ein Bereich des Marketing-Mix','j',''),
    ('Die Soll-Seite ist die linke Seite eines Kontos','j',''),
    ('Der Besitzer einer Sache ist nicht immer auch der Eigentümer','j',''),
    ('Durch just-in-time Lieferungen kann im Lager gebundenes Kapital reduziert werden','j',''),
    ('Kapitalgesllschaften sind in der Abteilung B des Handelsregisters eingetragen','j',''),
    ('Ein bilaterales Oligopol hat immer wenige Anbieter und wenige Nachfrager','j',''),
    ('Lizenzen sind handelbaren Rechte','j',''),
    ('Der dispositive Faktor beinhaltet die Leitungstätigkeit','j',''),
    ('Den Forschungsbereich Betriebswirtschaftslehre gibt es seit dem 15. Jahrhundert','n','Nope, den gibts seit 1902'),
    ('Die beiden Seiten eines Kontos heißen Soll und Haben','j',''),
    ('Betriebsstoffe gehen nicht substanziell in die Produktion ein','j',''),
    ('Rechtsfähig werden natürliche Perosnen mit Vollendung der Geburt','j',''),
    ('Die Betriebswirtschaftslehre gibt es erst seit Beginn des 20ten. Jahrhunderts','j',''),
    ('Unter dem tertitären Sektor versteht man den Dienstleistungsbereich','j',''),
    ('Das BGB ist dem HGB übergeordnet','j',''),
    ('Just in Time Lieferung vermindert die Lagerhaltung','j',''),
    ('Zweiseitige Rechtsgeschäfte benötigen zwei übereinstimmende Willenserklärungen','j',''),
    ('Beim einseitigen Handelskauf kann der Gerichtsstand frei vereinbart werden','n','Nur beim zweiseitigen, es ist der Ort der Erfüllung'),
    ('Ein Aktionär hat kein Anrecht am Liquidationserlös','n','Doch hat er!'),
    ('Bei Personengesellschaften haftet nur das eingezahlte Kapital der Inhaber','n','Nein, bei der Personengesellschaft haftet der inhaber ganz'),
    ('Warenschulden sind Bergschulden, Geldschulden sind Holschulden','n','Nö, Warenschulden sind Holschulden, Geldschulden sind Bringschulden'),
    ('Am Ende des Produktlebenszyklus steht die Produktvariation','n','Produktdegenaration/elimination ist am Ende'),
    ('Die Werbung ist Teil der Distributionspolitik','n','Da stimmt einfach gar nix dran'),

    ('Die Distributionspolitik ist ein Bereich des Marketing-Mix','j',''),
    ('Am Ende des Produktlebenszyklus steht die Produktelimination','j',''),
    ('Die Soll-Seite ist die linke Seite einer Bilanz','j',''),
    ('Der Besitzer einer Sache ist immer auch der Eigentümer','n','§ 854 Abs. 1 BGB: Der Besitz einer Sache wird durch die Erlangung der tatsächlichen Gewalt über die Sache erworben.'),
    ('Durch just-in-time Lieferungen kann im Lager gebundenes Kapital nicht reduziert werden','n','Lagerhaltung bindet viel Kapital, und da JiT die Lagerhaltung versucht zu minimieren, ist mit diesem neuen Konzept nicht mehr so viel Kapital in gelagerte Waren gebunden.'),
    ('Kapitalgesellschaften sind in der Abteilung A des Handelsregisters eingetragen','n','Kapitalgesellschaften werden in die Abteilung B des Handelsregisters eingetragen'),
    ('Ein bilaterales Oligopol hat immer viele Anbieter und viele Nachfrager','n','Ein bilaterales Oligopol hat wenige Anbieter und wenige Nachfrager'),
    ('Das klimatisieren einer Ware verursacht keine Lagerkosten','n','Doch.'),
    ('Lizenzen sind keine handelbaren Rechte','n','Doch.'),
    ('Der Zwischenhandel wird beim indirekten Verkauf ausgeschaltet','n','Der Zwischenhandel wird beim direkten Verkauf ausgeschaltet'),
    ('Der dispositive Faktor beinhaltet keine Leitungstätigkeit','n','Der dispositive Faktor wird durch die Tätigkeit der Geschäfts- und Betriebsleitung dargestellt.'),
    ('Den Forschungsbereich Betriebswirtschaftslehre gibt es seit dem 15. Jahrhundert','n','Den Forschungsbereich Betriebswirtschaftslehre gibt es seit dem Jahr 1902.'),
    ('Die einfache Buchhaltung bietet mehr Sicherheit als die doppelte Buchhaltung','n','Mit der doppelten Buchführung wird die rechnerische Richtigkeit aller Buchungen sichergestellt.'),
    ('Beim Minimalprinzip ist die eingesetzte Menge vorgegeben','n','Ziel ist vorgegeben, Zur Erfüllung des Ziels soll möglichst wenig Aufwand betrieben werden. (Die Mittel sind somit variabel)'),
    ('Der Gewinn ergibt sich aus Erlös plus Kosten','n','Der Gewinn ergibt sich aus Erlös minus Kosten'),
    ('Das HGB ist das Obergesetz, das vom BGB konkretisiert wird','n','Das BGB ist das Obergesetz, das vom HGB konkretisiert wird. (Die handelsrechtlichen Vorschriften haben Vorrang vor dem Bürgerlichen Gesetzbuch, da sie spezieller sind.)'),
    ('Die Rechtsfähigkeit beginnt mit der Vollendung des 7. Lebensjahr','n','Die Rechtsfähigkeit des Menschen beginnt mit der Vollendung der Geburt.'),
    ('Der Komplementär ist der Teilhafter einer KG','n','Der Komplementär ist der Vollhafter einer KG'),
    ('Der sekundäre Sektor ist der Dienstleistungsbereich','n','Der sekundäre Sektor ist der industrielle Sektor. Der tertiäre Sektor ist der Dienstleistungbereich.'),
    ('Die Distributionspolitik ist kein Bereich des Marketing-Mix','n','Die Distributionspolitik ist ein Bereich des Marketing-Mix (Die Distributionspolitik befasst sich als Teilbereich des Marketing-Mix mit den operativen Entscheidungen der Transferlogistik sowie den strategischen Maßnahmen des Vertriebssystems.)'),
    ('Am Ende des Produktlebenszyklus steht die Produktinnovation','n',''),
    ('Die Soll-Seite ist die linke Seite eines Kontos','j',''),
    ('Der Besitzer einer Sache ist nicht immer auch der Eigentümer','j',''),
    ('Durch just-in-time Lieferungen kann im Lager gebundenes Kapital reduziert werden','j',''),
    ('Kapitalgesellschaften sind in der Abteilung B des Handelsregisters eingetragen','j',''),
    ('Ein bilaterales Oligopol hat immer wenige Anbieter und wenige Nachfrager','j',''),
    ('Das klimatisieren einer Ware verursacht Lagerkosten','j',''),
    ('Lizenzen sind handelbaren Rechte','j',''),
    ('Der Zwischenhandel wird beim direkten Verkauf ausgeschaltet','j',''),
    ('Der dispositive Faktor beinhaltet die Leitungstätigkeit','j',''),
    ('Den Forschungsbereich Betriebswirtschaftslehre gibt es seit dem 20. Jahrhundert','j','');

Select *
From bwlFragen;

SELECT *
FROM bwlFragen
WHERE frage like '%Faktor%' and frage like '%Leitungstätigkeit%';

-- doppelte Einträge
SELECT id, frage as 'Doppelte Fragen',COUNT(frage) as 'Anzahl'
FROM bwlFragen
GROUP BY frage
HAVING (COUNT(frage) > 1);